In [1]:
import pandas as pd
from datetime import datetime, timedelta
import matplotlib

In [2]:
df = pd.read_csv("C:/Users/isamu/OneDrive/THESIS/DATA/Google/P2 Data/pressure_tourism_new.csv", index_col=0)

In [3]:
times = pd.read_csv("C:/Users/isamu/OneDrive/THESIS/DATA/Google/P2 Data/test_times.csv", index_col=0)[["place_id", "geometry"]]

In [4]:
times

,place_id,geometry
0,ChIJFTdsYMMJxkcRryoUM7EyJY0,POINT (4.8840769 52.3723397)
1,ChIJz09EBcMJxkcRwRi15EQTPog,POINT (4.8842989 52.370449199999996)
2,ChIJIYdU8sMJxkcRD1Ys8SczZTE,POINT (4.8874125 52.371868899999996)
3,ChIJMZGUGcMJxkcRPRyYTICSTYM,POINT (4.8838778 52.3704694)
4,ChIJy3zD9cIJxkcRxfIlpjk47JQ,POINT (4.8840148 52.369290299999996)
...,...,...
7325,ChIJPcEtxHEKxkcRx84qVvhT_uE,POINT (4.8717681 52.3169719)
7326,ChIJVWZIVwsKxkcR4vauw0vYxuk,POINT (4.867037 52.325753999999996)
7327,ChIJC_KvV9jhxUcRgDzDAbDHkBw,POINT (4.8566474 52.317434)
7328,ChIJN8RMMqgLxkcRknxrSHEle1E,POINT (4.870786799999999 52.3184215)
7329,ChIJzVN3QY_hxUcREIzfWnT4u94,POINT (4.824796699999999 52.341766299999996)

In [5]:

# Define a reference date for a given week
reference_monday = datetime(2024, 1, 1)  # Adjust to the first Monday of the year or any reference Monday

# Create a mapping from day names to a date in the reference week
day_mapping = {day: reference_monday + timedelta(days=i) for i, day in enumerate([
    "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
])}

# Sample DataFrame (assuming it's already loaded)
df['datetime'] = df.apply(lambda row: day_mapping[row['Dayname']] + timedelta(hours=row['Hour']), axis=1)

In [7]:
home = df.merge(times, on = "place_id", how = "left")[["Buurt", "Wijk", "place_id", "reviews 2024", "name", "pressure", "datetime", "geometry"]]

In [9]:
#home.to_csv("C:/Users/isamu/OneDrive/THESIS/DATA/Google/P2 Data/new_pressure_time.csv")

In [27]:
home_small = home[["name", "pressure", "datetime", "geometry"]]
home_small.to_csv("C:/Users/isamu/OneDrive/THESIS/DATA/Google/P2 Data/test_pressure_time_small.csv")

In [8]:
home

,Buurt,Wijk,place_id,reviews 2024,name,pressure,datetime,geometry
0,Felix Meritisbuurt,Grachtengordel-West,ChIJFTdsYMMJxkcRryoUM7EyJY0,133.0,Nooch,0.000000,2024-01-02 00:00:00,POINT (4.8840769 52.3723397)
1,Felix Meritisbuurt,Grachtengordel-West,ChIJFTdsYMMJxkcRryoUM7EyJY0,133.0,Nooch,0.000000,2024-01-02 01:00:00,POINT (4.8840769 52.3723397)
2,Felix Meritisbuurt,Grachtengordel-West,ChIJFTdsYMMJxkcRryoUM7EyJY0,133.0,Nooch,0.000000,2024-01-02 02:00:00,POINT (4.8840769 52.3723397)
3,Felix Meritisbuurt,Grachtengordel-West,ChIJFTdsYMMJxkcRryoUM7EyJY0,133.0,Nooch,0.000000,2024-01-02 03:00:00,POINT (4.8840769 52.3723397)
4,Felix Meritisbuurt,Grachtengordel-West,ChIJFTdsYMMJxkcRryoUM7EyJY0,133.0,Nooch,0.000000,2024-01-02 04:00:00,POINT (4.8840769 52.3723397)
...,...,...,...,...,...,...,...,...
594403,Hoofdcentrum-Zuidoost,Amstel III/Bullewijk,ChIJJVNbSZcLxkcRmlFDljhOFgE,4724.0,Ziggo Dome,12.947432,2024-01-07 19:00:00,POINT (4.9371203 52.3135914)
594404,Hoofdcentrum-Zuidoost,Amstel III/Bullewijk,ChIJJVNbSZcLxkcRmlFDljhOFgE,4724.0,Ziggo Dome,25.894864,2024-01-07 20:00:00,POINT (4.9371203 52.3135914)
594405,Hoofdcentrum-Zuidoost,Amstel III/Bullewijk,ChIJJVNbSZcLxkcRmlFDljhOFgE,4724.0,Ziggo Dome,25.894864,2024-01-07 21:00:00,POINT (4.9371203 52.3135914)
594406,Hoofdcentrum-Zuidoost,Amstel III/Bullewijk,ChIJJVNbSZcLxkcRmlFDljhOFgE,4724.0,Ziggo Dome,25.894864,2024-01-07 22:00:00,POINT (4.9371203 52.3135914)
594407,Hoofdcentrum-Zuidoost,Amstel III/Bullewijk,ChIJJVNbSZcLxkcRmlFDljhOFgE,4724.0,Ziggo Dome,25.894864,2024-01-07 23:00:00,POINT (4.9371203 52.3135914)