In [1]:
import pandas as pd
import json
import geopandas as gpd
from shapely import wkt

In [2]:
wijk = pd.read_csv("C:/Users/isamu/OneDrive/THESIS/DATA/GEBIED_WIJKEN.csv", delimiter = ";")
hotelbeds = pd.read_csv("C:/Users/isamu/OneDrive/THESIS/DATA/Amsterdam/hotelbed_wijk.csv", delimiter = ";")

In [3]:
hotels_rev = pd.read_csv("C:/Users/isamu/OneDrive/THESIS/DATA/Google/P2 Data/2024_count.csv")
hotels_loc = pd.read_csv("C:/Users/isamu/OneDrive/THESIS/DATA/Google/P2 Data/times.csv")[["place_id", "coordinates", "main_category"]]

In [4]:
hotelbeds["Wijkcode"] = hotelbeds["Wijken"].str.split().str[0]
hotelbeds["Wijknaam"] = hotelbeds["Wijken"].str.extract(r'^\S+\s+(.*)')

In [5]:
wijk = wijk.merge(hotelbeds, on = "Wijkcode")
wijk['geometry'] = wijk['WKT_LNG_LAT'].apply(wkt.loads)
wijk_gdf = gpd.GeoDataFrame(wijk, geometry = "geometry", crs = "EPSG:4326")

In [6]:
# Parse the 'coordinates' column into separate latitude and longitude columns
hotels_loc[['latitude', 'longitude']] = hotels_loc['coordinates'].apply(lambda x: pd.Series(json.loads(x)))

hotels_loc = hotels_loc[hotels_loc["main_category"] == "Hotel"]

In [7]:
hotels_gdf = hotels_rev.merge(hotels_loc, on = "place_id", how = "inner")

hotels_gdf = gpd.GeoDataFrame(hotels_gdf, geometry=gpd.points_from_xy(hotels_gdf['longitude'], hotels_gdf['latitude']), crs="EPSG:4326")

In [8]:
hotels_wijk_gdf = gpd.sjoin(hotels_gdf, wijk_gdf, how = "inner", predicate = "intersects")
hotels_wijk_gdf = hotels_wijk_gdf[["place_id", "reviews 2024", "name", "geometry", "Wijkcode", "Wijknaam_x", "Aantal hotelbedden"]]

In [9]:
hotels_wijk_gdf_sum = hotels_wijk_gdf.groupby(["Wijkcode", "Wijknaam_x", "Aantal hotelbedden"])["reviews 2024"].sum().reset_index()

In [10]:
hotels_wijk_gdf = hotels_wijk_gdf.merge(hotels_wijk_gdf_sum, on = ["Wijkcode", "Wijknaam_x", "Aantal hotelbedden"], suffixes = ("","_sum"))
hotels_wijk_gdf["percentage_reviews_wijk"] = hotels_wijk_gdf["reviews 2024"] / hotels_wijk_gdf["reviews 2024_sum"]
hotels_wijk_gdf["hotelbeds hotel"] = round(hotels_wijk_gdf["percentage_reviews_wijk"] * hotels_wijk_gdf["Aantal hotelbedden"])
hotels_wijk_gdf

,place_id,reviews 2024,name,geometry,Wijkcode,Wijknaam_x,Aantal hotelbedden,reviews 2024_sum,percentage_reviews_wijk,hotelbeds hotel
0,ChIJbeLDaSIKxkcR4uMOfG8J_cw,784,Hotel nhow Amsterdam RAI,POINT (4.89191 52.33896),K23,Zuidas,3129,1989,0.394168,1233.0
1,ChIJZyc7C7oJxkcRSPqsBgyVa0k,760,DoubleTree by Hilton Amsterdam Centraal Station,POINT (4.90547 52.37668),A04,Nieuwmarkt/Lastage,3574,2191,0.346874,1240.0
2,ChIJgYCiu5kLxkcRPQIZ1Wezozs,722,"Holiday Inn Express Amsterdam - Arena Towers, ...",POINT (4.94102 52.3096),T92,Amstel III/Bullewijk,4695,3196,0.225907,1061.0
3,ChIJxYYOH_bixUcRmvXuhmyjUx4,709,MEININGER Hotel Amsterdam City West,POINT (4.83746 52.39036),F11,Bedrijventerrein Sloterdijk,4705,2963,0.239285,1126.0
4,ChIJhfOaePYJxkcRWWJAZeXdlp4,637,Leonardo Hotel Amsterdam Rembrandtpark,POINT (4.84401 52.36812),F86,Overtoomse Veld,1012,1129,0.564216,571.0
...,...,...,...,...,...,...,...,...,...,...
386,ChIJVfi2HMgJxkcRYcxaRHoFaeo,1,Hotel Season Star,POINT (4.89623 52.378),A01,Burgwallen-Nieuwe Zijde,8645,5140,0.000195,2.0
387,ChIJyZWa5boJxkcRoi_aC8NY2AM,1,SWEETS hotel Amstelschutsluis,POINT (4.90246 52.3621),A07,De Weteringschans,2259,1673,0.000598,1.0
388,ChIJf-ETabkJxkcRnjwYhBCoeos,1,Studioboom,POINT (4.90129 52.37326),A04,Nieuwmarkt/Lastage,3574,2191,0.000456,2.0
389,ChIJh5sG0ecJxkcRBNdP2z2Wv_o,1,Hotel Leidsegracht,POINT (4.88042 52.36512),A07,De Weteringschans,2259,1673,0.000598,1.0
390,ChIJOXxjYwDjxUcR5C4NndL4Mnc,1,The Social Hub Amsterdam West 4 star,POINT (4.83643 52.37235),F86,Overtoomse Veld,1012,1129,0.000886,1.0

In [15]:
hotels_wijk_gdf_belt = hotels_wijk_gdf[hotels_wijk_gdf["Wijkcode"].isin(["E36", "E37", "E38", "E39", "E41", "F11", "F86", "F87", "F88", "F89", 
                                                                         "K23", "K44", "K48", "K52", "K90", "T92", "K91", "M58", "T93"])]
hotels_wijk_gdf_belt = hotels_wijk_gdf_belt.groupby(["Wijkcode", "Wijknaam_x"])["Aantal hotelbedden"].mean().reset_index()

In [16]:
print(round(hotels_wijk_gdf_belt["Aantal hotelbedden"].sum() / hotelbeds["Aantal hotelbedden"].sum() * 100), str("percent"))

31 percent

In [31]:
pd.read_csv("C:/Users/isamu/OneDrive/THESIS/DATA/Google/P2 Data/times.csv")

,place_id,name,reviews,rating,main_category,categories,closed_on,review_keywords,price_range,reviews_per_rating,coordinates,hours,popular_times,query
0,ChIJFTdsYMMJxkcRryoUM7EyJY0,Nooch,795,4.4,Aziatisch fusion-restaurant,"[""Aziatisch fusion-restaurant"",""Aziatisch rest...","[""maandag""]","[{""keyword"":""pad thai"",""count"":37},{""keyword"":...",$$$$$$$,"{""1"":31,""2"":20,""3"":55,""4"":169,""5"":520}","{""latitude"":52.3723397,""longitude"":4.8840769}","[{""day"":""maandag"",""times"":[""Gesloten""]},{""day""...","{""Tuesday"":[{""hour_of_day"":6,""time_label"":""06:...",restaurants in negen straatjes
1,ChIJz09EBcMJxkcRwRi15EQTPog,Restaurant de Struisvogel,572,4.7,Restaurant,"[""Restaurant""]",Open All Days,"[{""keyword"":""gangen"",""count"":34},{""keyword"":""v...",$$$$$$$,"{""1"":5,""2"":7,""3"":23,""4"":106,""5"":431}","{""latitude"":52.370449199999996,""longitude"":4.8...","[{""day"":""maandag"",""times"":[""17:30-00:00""]},{""d...",Not Present,restaurants in negen straatjes
2,ChIJIYdU8sMJxkcRD1Ys8SczZTE,Lotti's,848,3.9,Restaurant,"[""Restaurant""]",Open All Days,"[{""keyword"":""atmosfeer"",""count"":84},{""keyword""...",$$,"{""1"":69,""2"":74,""3"":89,""4"":216,""5"":400}","{""latitude"":52.371868899999996,""longitude"":4.8...","[{""day"":""maandag"",""times"":[""07:00-00:00""]},{""d...",Not Present,restaurants in negen straatjes
3,ChIJMZGUGcMJxkcRPRyYTICSTYM,Restaurant 't Zwaantje,2082,4.5,Nederlands restaurant,"[""Nederlands restaurant"",""Europees restaurant""...",Open All Days,"[{""keyword"":""stoofpotje"",""count"":135},{""keywor...",$$$$$$$,"{""1"":69,""2"":35,""3"":110,""4"":391,""5"":1477}","{""latitude"":52.3704694,""longitude"":4.8838778}","[{""day"":""maandag"",""times"":[""16:30-22:30""]},{""d...","{""Monday"":[{""hour_of_day"":6,""time_label"":""06:0...",restaurants in negen straatjes
4,ChIJy3zD9cIJxkcRxfIlpjk47JQ,Bar Brasserie OCCO,248,4.5,Brasserie,"[""Brasserie"",""Bar"",""Cocktailbar"",""Restaurant""]",Open All Days,"[{""keyword"":""cocktails"",""count"":24},{""keyword""...",NaN,"{""1"":9,""2"":3,""3"":20,""4"":37,""5"":179}","{""latitude"":52.369290299999996,""longitude"":4.8...","[{""day"":""maandag"",""times"":[""07:00-00:00""]},{""d...","{""Monday"":[{""hour_of_day"":6,""time_label"":""06:0...",restaurants in negen straatjes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7325,ChIJPcEtxHEKxkcRx84qVvhT_uE,Cityden Zuidas,1159,4.3,Hotel,"[""Hotel"",""Bar"",""Hotel voor langdurig verblijf""...",Open All Days,"[{""keyword"":""tram"",""count"":68},{""keyword"":""ope...",NaN,"{""1"":52,""2"":29,""3"":90,""4"":310,""5"":678}","{""latitude"":52.3169719,""longitude"":4.8717681}",[],Not Present,hotels in zuidas
7326,ChIJVWZIVwsKxkcR4vauw0vYxuk,"Holiday Inn Express Amsterdam - South, an IHG ...",1125,4.3,Hotel,"[""Hotel"",""Congrescentrum"",""Trouwlocatie""]",Open All Days,"[{""keyword"":""tram"",""count"":44},{""keyword"":""ope...",NaN,"{""1"":37,""2"":27,""3"":127,""4"":345,""5"":589}","{""latitude"":52.325753999999996,""longitude"":4.8...",[],Not Present,hotels in zuidas
7327,ChIJC_KvV9jhxUcRgDzDAbDHkBw,Amsterdam Forest Hotel,766,4.2,Hotel,"[""Hotel"",""Accomodatie""]",Open All Days,"[{""keyword"":""douche"",""count"":32},{""keyword"":""o...",NaN,"{""1"":44,""2"":24,""3"":89,""4"":216,""5"":393}","{""latitude"":52.317434,""longitude"":4.8566474}",[],Not Present,hotels in zuidas
7328,ChIJN8RMMqgLxkcRknxrSHEle1E,Aparthotel Adagio Amsterdam City South,759,4.5,Hotel,"[""Hotel""]",Open All Days,"[{""keyword"":""tramhalte"",""count"":22},{""keyword""...",NaN,"{""1"":29,""2"":10,""3"":36,""4"":158,""5"":526}","{""latitude"":52.3184215,""longitude"":4.870786799...",[],Not Present,hotels in zuidas
7329,ChIJzVN3QY_hxUcREIzfWnT4u94,Hotel Artemis Amsterdam,2732,4.1,Hotel,"[""Hotel""]",Open All Days,"[{""keyword"":""tram"",""count"":142},{""keyword"":""vl...",NaN,"{""1"":143,""2"":112,""3"":356,""4"":870,""5"":1251}","{""latitude"":52.341766299999996,""longitude"":4.8...",[],Not Present,hotels in zuidas

In [11]:
#hotels_wijk_gdf.to_csv("C:/Users/isamu/OneDrive/THESIS/DATA/Amsterdam/hotelbed_hotel.csv")

In [33]:
hotels_wijk_gdf[hotels_wijk_gdf["Wijkcode"].isin(["E36", "E37", "E38", "E39", "E41", "F11", "F86", "F87", "F88", "F89", 
                                                  "K23", "K44", "K48", "K52", "K90", "T92", "K91", "M58", "T93"])]

,place_id,reviews 2024,name,geometry,Wijkcode,Wijknaam_x,Aantal hotelbedden,reviews 2024_sum,percentage_reviews_wijk,hotelbeds hotel
0,ChIJbeLDaSIKxkcR4uMOfG8J_cw,784,Hotel nhow Amsterdam RAI,POINT (4.89191 52.33896),K23,Zuidas,3129,1989,0.394168,1233.0
2,ChIJgYCiu5kLxkcRPQIZ1Wezozs,722,"Holiday Inn Express Amsterdam - Arena Towers, ...",POINT (4.94102 52.3096),T92,Amstel III/Bullewijk,4695,3196,0.225907,1061.0
3,ChIJxYYOH_bixUcRmvXuhmyjUx4,709,MEININGER Hotel Amsterdam City West,POINT (4.83746 52.39036),F11,Bedrijventerrein Sloterdijk,4705,2963,0.239285,1126.0
4,ChIJhfOaePYJxkcRWWJAZeXdlp4,637,Leonardo Hotel Amsterdam Rembrandtpark,POINT (4.84401 52.36812),F86,Overtoomse Veld,1012,1129,0.564216,571.0
5,ChIJ-RAyRD0KxkcRG4koK51opDE,631,Hotel Novotel Amsterdam City,POINT (4.88852 52.33372),K91,Buitenveldert-Oost,1646,637,0.990581,1630.0
6,ChIJ_WZ4cs0LxkcR8gFUHvfuBsE,629,Leonardo Royal Hotel Amsterdam,POINT (4.91785 52.33243),M58,Omval/Overamstel,3353,2097,0.299952,1006.0
7,ChIJv6OOxGDixUcR0NBBnqvC4sw,629,XO Hotels Park West,POINT (4.84706 52.3856),E36,Sloterdijk,817,938,0.670576,548.0
11,ChIJJVSNLlnixUcRa8wszX39t7M,546,Holiday Inn Express Amsterdam - Sloterdijk Sta...,POINT (4.83756 52.38783),F11,Bedrijventerrein Sloterdijk,4705,2963,0.184273,867.0
14,ChIJ2bm1R4MLxkcRO3Nce2k7SRE,527,Hotel Levell Amsterdam,POINT (4.95053 52.30475),T92,Amstel III/Bullewijk,4695,3196,0.164894,774.0
18,ChIJK_RWo1XhxUcRQlaKrcBHkNI,513,Olympic Hotel Amsterdam,POINT (4.85309 52.34136),K48,Stadionbuurt,732,580,0.884483,647.0
19,ChIJB-6ZgF_ixUcR3RqgxAhq35Q,503,Park Inn by Radisson Amsterdam City West,POINT (4.84251 52.39015),F11,Bedrijventerrein Sloterdijk,4705,2963,0.169760,799.0
21,ChIJv42bEB_ixUcRO8p-I1HMl-M,468,XO Hotels Couture,POINT (4.84142 52.35115),F87,Westlandgracht,2134,1412,0.331445,707.0
23,ChIJ7_JeDZALxkcR6zrSG75eNNI,460,Hampton by Hilton Amsterdam / Arena Boulevard,POINT (4.94784 52.31304),T93,"Bijlmer Centrum (D,F,H)",682,460,1.000000,682.0
24,ChIJiRko-NELxkcRcrjr7i5AuQc,446,Postillion Hotel Amsterdam,POINT (4.92181 52.33347),M58,Omval/Overamstel,3353,2097,0.212685,713.0
25,ChIJHwci1XYLxkcR0Kd7zDqhBmc,441,Fletcher Hotel Amsterdam,POINT (4.94446 52.29248),T92,Amstel III/Bullewijk,4695,3196,0.137985,648.0
27,ChIJGVGV9InhxUcRhlbOT01ynbE,427,"Corendon Amsterdam New-West, a Tribute Portfol...",POINT (4.83103 52.34656),F89,Slotervaart Zuid,526,427,1.000000,526.0
28,ChIJ7V5Oai0KxkcRcctSgGOZ5fU,422,Mercure Hotel Amsterdam City,POINT (4.91349 52.33529),M58,Omval/Overamstel,3353,2097,0.201240,675.0
29,ChIJjXkvNCIKxkcRObyJK4Dy9Rw,416,Motel One Amsterdam,POINT (4.89258 52.33849),K52,Scheldebuurt,700,416,1.000000,700.0
31,ChIJt2YRyRnixUcR1DznptCpL_A,408,WestCord Fashion Hotel Amsterdam,POINT (4.84458 52.35766),F87,Westlandgracht,2134,1412,0.288952,617.0
32,ChIJ1TT0OB7ixUcRqdgd8HPVkTw,408,Best Western Amsterdam,POINT (4.84265 52.34873),F87,Westlandgracht,2134,1412,0.288952,617.0
33,ChIJW3rldWjixUcRNu0ZuZ5cVK0,406,XO HOTELS Blue Tower,POINT (4.84569 52.3792),E37,Landlust,633,406,1.000000,633.0
34,ChIJe3oxktMLxkcRU1_gZsP0cYQ,398,Ruby Emma Hotel & Bar,POINT (4.92106 52.33832),M58,Omval/Overamstel,3353,2097,0.189795,636.0
39,ChIJ4eWiagQKxkcRf5j280yfbfE,389,INNSiDE by Melia Amsterdam,POINT (4.87099 52.33988),K23,Zuidas,3129,1989,0.195576,612.0
43,ChIJaTE3x_m9wEcRG4cRF4GNqC0,378,Van der Valk Hotel Amsterdam Zuidas,POINT (4.88828 52.33681),K23,Zuidas,3129,1989,0.190045,595.0
45,ChIJ1QYJB1nixUcREAs0Xg6jPng,370,Mercure Hotel Amsterdam Sloterdijk Station,POINT (4.83562 52.38725),F11,Bedrijventerrein Sloterdijk,4705,2963,0.124873,588.0
51,ChIJZwHsk5wLxkcR53kR2GqPKUs,350,Ozo Hotels Arena Amsterdam,POINT (4.94773 52.30479),T92,Amstel III/Bullewijk,4695,3196,0.109512,514.0
53,ChIJL_pc9FnixUcRCJ4sqnV2h04,345,Amsterdam Teleport Hotel,POINT (4.83256 52.38534),F11,Bedrijventerrein Sloterdijk,4705,2963,0.116436,548.0
55,ChIJQWzaMpYLxkcRNbma_pnJHkE,339,Jaz in the City Amsterdam,POINT (4.93881 52.31437),T92,Amstel III/Bullewijk,4695,3196,0.106070,498.0
58,ChIJ2bElKUHixUcRwH30Tvfx370,330,The Social Hub Amsterdam West,POINT (4.83621 52.37207),F86,Overtoomse Veld,1012,1129,0.292294,296.0
64,ChIJCwdATorixUcR-Hg7-ViyMZI,309,Hotel ibis Amsterdam City West,POINT (4.85012 52.3923),E36,Sloterdijk,817,938,0.329424,269.0
68,ChIJi6P-MZcLxkcRqZzNKOmf4NQ,291,easyHotel Amsterdam Arena Boulevard,POINT (4.94474 52.31319),T92,Amstel III/Bullewijk,4695,3196,0.091051,427.0
77,ChIJzVN3QY_hxUcREIzfWnT4u94,259,Hotel Artemis Amsterdam,POINT (4.8248 52.34177),F88,Sloter-/Riekerpolder,908,259,1.000000,908.0
80,ChIJ8T8oy2nixUcRbw9oQ5bn6m0,243,Cityden BoLo District,POINT (4.84462 52.37633),E39,De Kolenkit,948,423,0.574468,545.0
81,ChIJOTNFq5wLxkcRHNgvRQEM53Q,240,Joy Hotel Amsterdam,POINT (4.9503 52.30523),T92,Amstel III/Bullewijk,4695,3196,0.075094,353.0
87,ChIJ8w6Rg1nixUcRFxe0quvaP2U,215,Urban Lodge Hotel,POINT (4.83462 52.38555),F11,Bedrijventerrein Sloterdijk,4705,2963,0.072562,341.0
99,ChIJXxMBZi0KxkcRC9EaMAr3jzo,199,Van der Valk Hotel Amsterdam - Amstel,POINT (4.91479 52.33323),M58,Omval/Overamstel,3353,2097,0.094897,318.0
100,ChIJ_dZhWgUKxkcRpOz1cKJp-vs,198,Crowne Plaza Amsterdam - South,POINT (4.87456 52.33579),K23,Zuidas,3129,1989,0.099548,311.0
106,ChIJsZP0Y5oLxkcRwiYpjvf7ldA,190,Courtyard Amsterdam Arena Atlas,POINT (4.94663 52.30978),T92,Amstel III/Bullewijk,4695,3196,0.059449,279.0
111,ChIJWREZRkPixUcRs5Mdv7li4Qo,180,Hotel New Kit,POINT (4.83838 52.37899),E39,De Kolenkit,948,423,0.425532,403.0
116,ChIJkQyWuxEKxkcRoc54h_ZVKW4,174,Element Amsterdam,POINT (4.87755 52.33167),K90,Buitenveldert-West,763,317,0.548896,419.0
118,ChIJrShpvgQKxkcRmGVTfdQ0BfA,169,Qbic Hotel WTC Amsterdam,POINT (4.87507 52.33993),K23,Zuidas,3129,1989,0.084967,266.0
124,ChIJ8aIni3zjxUcRHLo3kPu7aGg,161,Met Hotel Amsterdam,POINT (4.83528 52.36264),F86,Overtoomse Veld,1012,1129,0.142604,144.0
133,ChIJVWZIVwsKxkcR4vauw0vYxuk,143,"Holiday Inn Express Amsterdam - South, an IHG ...",POINT (4.86704 52.32575),K90,Buitenveldert-West,763,317,0.451104,344.0
136,ChIJYywUslnixUcRsOW0m48buCs,138,ID APARTHOTEL,POINT (4.83432 52.38727),F11,Bedrijventerrein Sloterdijk,4705,2963,0.046574,219.0
144,ChIJ3YAVgxrixUcRKuOlFIBGff8,131,Hotel Belfort,POINT (4.85072 52.35767),K44,Hoofddorppleinbuurt,416,131,1.000000,416.0
149,ChIJt2YRyRnixUcROCYYl3nQeRw,128,Bastion Hotel Amsterdam Zuidwest,POINT (4.84362 52.3576),F87,Westlandgracht,2134,1412,0.090652,193.0
157,ChIJ8bfXC1_ixUcRB5kZ-zX1doM,122,Train Lodge,POINT (4.8407 52.3886),F11,Bedrijventerrein Sloterdijk,4705,2963,0.041174,194.0
194,ChIJXwH1EGcLxkcR-YYQh4bMNLM,96,"Holiday Inn Amsterdam - Arena Towers, an IHG H...",POINT (4.94101 52.30958),T92,Amstel III/Bullewijk,4695,3196,0.030038,141.0
236,ChIJk8fjEWALxkcRvcAfXF2Ker0,71,PREMIER SUITES Amsterdam,POINT (4.86798 52.3375),K23,Zuidas,3129,1989,0.035696,112.0
247,ChIJB1PAKP_hxUcRhG82RSZzxfk,67,The July - Twenty Eight,POINT (4.85755 52.34323),K48,Stadionbuurt,732,580,0.115517,85.0
365,ChIJp_6cFxXjxUcRmPG0EOWb1FM,15,limehome Amsterdam Gatwickstraat,POINT (4.84189 52.39053),F11,Bedrijventerrein Sloterdijk,4705,2963,0.005062,24.0
376,ChIJEYutQRMKxkcRUhbcFyG5mcY,6,Nh Amsterdam Zuid,POINT (4.87999 52.32671),K91,Buitenveldert-Oost,1646,637,0.009419,16.0
381,ChIJB4Ej19wLxkcRZkIPDsFkIE0,3,SWEETS hotel Omvalbrug,POINT (4.91895 52.34269),M58,Omval/Overamstel,3353,2097,0.001431,5.0
390,ChIJOXxjYwDjxUcR5C4NndL4Mnc,1,The Social Hub Amsterdam West 4 star,POINT (4.83643 52.37235),F86,Overtoomse Veld,1012,1129,0.000886,1.0

In [ ]:
#LOOK AT HOTELS WITH HIGH REVIEWS LOW BEDS AND FIX